import { Provider } from "@/components/ui/provider";
import { Vazirmatn } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next";

const vazirmatn = Vazirmatn({
  variable: "--font-vazir",
  subsets: ["latin"],
});

export const metadata = {
  title: "Management Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      className={vazirmatn.className}
      suppressHydrationWarning
      dir="rtl"
      lang="fa"
    >
      <body>
        <Provider>
          <NuqsAdapter>{children}</NuqsAdapter>
        </Provider>
      </body>
    </html>
  );
}
